#include "webapp.h"

webapp webapp_object = {
    .web_app = {
        .servlet = {
            {
                .servlet_name = "cofaxCDS", 
                .init_param = (webapp_web_app_servlet_entry_init_param[]){
                    {
                        .cachePackageTagsTrack = 200, 
                        .dataStoreDriver = "com.microsoft.jdbc.sqlserver.SQLServerDriver", 
                        .dataLogMaxSize = NULL, 
                        .cacheTemplatesRefresh = 15, 
                        .configGlossary_adminEmail = "ksm@pobox.com", 
                        .dataStoreMaxConns = 100, 
                        .cachePagesDirtyRead = 10, 
                        .betaServer = false, 
                        .dataLogLocation = NULL, 
                        .templateProcessorClass = "org.cofax.WysiwygTemplate", 
                        .cachePagesStore = 100, 
                        .mailHost = NULL, 
                        .mailHostOverride = NULL, 
                        .jspListTemplate = "listTemplate.jsp", 
                        .dataStoreTestQuery = "SET NOCOUNT ON;select test='test';", 
                        .fileTransferFolder = NULL, 
                        .cacheTemplatesTrack = 100, 
                        .defaultFileTemplate = "articleTemplate.htm", 
                        .configGlossary_poweredByIcon = "/images/cofax.gif", 
                        .dataStoreUrl = "jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon", 
                        .adminGroupID = -1, 
                        .redirectionClass = "org.cofax.SqlRedirection", 
                        .configGlossary_installationAt = "Philadelphia, PA", 
                        .templatePath = "templates", 
                        .cachePackageTagsStore = 200, 
                        .searchEngineListTemplate = "forSearchEnginesList.htm", 
                        .removePageCache = NULL, 
                        .searchEngineRobotsDb = "WEB-INF/robots.db", 
                        .cacheTemplatesStore = 50, 
                        .removeTemplateCache = NULL, 
                        .defaultListTemplate = "listTemplate.htm", 
                        .dataStoreLogFile = "/usr/local/tomcat/logs/datastore.log", 
                        .dataStoreLogLevel = "debug", 
                        .useJSP = false, 
                        .dataStoreName = "cofax", 
                        .cachePackageTagsRefresh = 60, 
                        .dataStoreConnUsageLimit = 100, 
                        .configGlossary_staticPath = "/content/static", 
                        .configGlossary_poweredBy = "Cofax", 
                        .cachePagesRefresh = 10, 
                        .templateLoaderClass = "org.cofax.FilesTemplateLoader", 
                        .lookInContext = -1, 
                        .maxUrlLength = 500, 
                        .cachePagesTrack = 200, 
                        .useDataStore = true, 
                        .logLocation = NULL, 
                        .jspFileTemplate = "articleTemplate.jsp", 
                        .dataStoreUser = "sa", 
                        .dataStoreClass = "org.cofax.SqlDataStore", 
                        .searchEngineFileTemplate = "forSearchEngines.htm", 
                        .dataLog = -1, 
                        .log = -1, 
                        .dataStoreInitConns = 10.5, 
                        .dataStorePassword = "dataStoreTestQuery", 
                        .logMaxSize = NULL, 
                        .templateOverridePath = ""
                    }
                }, 
                .servlet_class = "org.cofax.cds.CDSServlet"
            }, 
            {
                .servlet_name = "cofaxEmail", 
                .init_param = (webapp_web_app_servlet_entry_init_param[]){
                    {
                        .cachePackageTagsTrack = -1, 
                        .dataStoreDriver = NULL, 
                        .dataLogMaxSize = NULL, 
                        .cacheTemplatesRefresh = -1, 
                        .configGlossary_adminEmail = NULL, 
                        .dataStoreMaxConns = -1, 
                        .cachePagesDirtyRead = -1, 
                        .betaServer = false, 
                        .dataLogLocation = NULL, 
                        .templateProcessorClass = NULL, 
                        .cachePagesStore = -1, 
                        .mailHost = "mail1", 
                        .mailHostOverride = "mail2", 
                        .jspListTemplate = NULL, 
                        .dataStoreTestQuery = NULL, 
                        .fileTransferFolder = NULL, 
                        .cacheTemplatesTrack = -1, 
                        .defaultFileTemplate = NULL, 
                        .configGlossary_poweredByIcon = NULL, 
                        .dataStoreUrl = NULL, 
                        .adminGroupID = -1, 
                        .redirectionClass = NULL, 
                        .configGlossary_installationAt = NULL, 
                        .templatePath = NULL, 
                        .cachePackageTagsStore = -1, 
                        .searchEngineListTemplate = NULL, 
                        .removePageCache = NULL, 
                        .searchEngineRobotsDb = NULL, 
                        .cacheTemplatesStore = -1, 
                        .removeTemplateCache = NULL, 
                        .defaultListTemplate = NULL, 
                        .dataStoreLogFile = NULL, 
                        .dataStoreLogLevel = NULL, 
                        .useJSP = false, 
                        .dataStoreName = NULL, 
                        .cachePackageTagsRefresh = -1, 
                        .dataStoreConnUsageLimit = -1, 
                        .configGlossary_staticPath = NULL, 
                        .configGlossary_poweredBy = NULL, 
                        .cachePagesRefresh = -1, 
                        .templateLoaderClass = NULL, 
                        .lookInContext = -1, 
                        .maxUrlLength = -1, 
                        .cachePagesTrack = -1, 
                        .useDataStore = false, 
                        .logLocation = NULL, 
                        .jspFileTemplate = NULL, 
                        .dataStoreUser = NULL, 
                        .dataStoreClass = NULL, 
                        .searchEngineFileTemplate = NULL, 
                        .dataLog = -1, 
                        .log = -1, 
                        .dataStoreInitConns = NAN, 
                        .dataStorePassword = NULL, 
                        .logMaxSize = NULL, 
                        .templateOverridePath = NULL
                    }
                }, 
                .servlet_class = "org.cofax.cds.EmailServlet"
            }, 
            {
                .servlet_name = "cofaxAdmin", 
                .init_param = NULL, 
                .servlet_class = "org.cofax.cds.AdminServlet"
            }, 
            {
                .servlet_name = "fileServlet", 
                .init_param = NULL, 
                .servlet_class = "org.cofax.cds.FileServlet"
            }, 
            {
                .servlet_name = "cofaxTools", 
                .init_param = (webapp_web_app_servlet_entry_init_param[]){
                    {
                        .cachePackageTagsTrack = -1, 
                        .dataStoreDriver = NULL, 
                        .dataLogMaxSize = "", 
                        .cacheTemplatesRefresh = -1, 
                        .configGlossary_adminEmail = NULL, 
                        .dataStoreMaxConns = -1, 
                        .cachePagesDirtyRead = -1, 
                        .betaServer = true, 
                        .dataLogLocation = "/usr/local/tomcat/logs/dataLog.log", 
                        .templateProcessorClass = NULL, 
                        .cachePagesStore = -1, 
                        .mailHost = NULL, 
                        .mailHostOverride = NULL, 
                        .jspListTemplate = NULL, 
                        .dataStoreTestQuery = NULL, 
                        .fileTransferFolder = "/usr/local/tomcat/webapps/content/fileTransferFolder", 
                        .cacheTemplatesTrack = -1, 
                        .defaultFileTemplate = NULL, 
                        .configGlossary_poweredByIcon = NULL, 
                        .dataStoreUrl = NULL, 
                        .adminGroupID = 4, 
                        .redirectionClass = NULL, 
                        .configGlossary_installationAt = NULL, 
                        .templatePath = "toolstemplates/", 
                        .cachePackageTagsStore = -1, 
                        .searchEngineListTemplate = NULL, 
                        .removePageCache = "/content/admin/remove?cache=pages&id=", 
                        .searchEngineRobotsDb = NULL, 
                        .cacheTemplatesStore = -1, 
                        .removeTemplateCache = "/content/admin/remove?cache=templates&id=", 
                        .defaultListTemplate = NULL, 
                        .dataStoreLogFile = NULL, 
                        .dataStoreLogLevel = NULL, 
                        .useJSP = false, 
                        .dataStoreName = NULL, 
                        .cachePackageTagsRefresh = -1, 
                        .dataStoreConnUsageLimit = -1, 
                        .configGlossary_staticPath = NULL, 
                        .configGlossary_poweredBy = NULL, 
                        .cachePagesRefresh = -1, 
                        .templateLoaderClass = NULL, 
                        .lookInContext = 1, 
                        .maxUrlLength = -1, 
                        .cachePagesTrack = -1, 
                        .useDataStore = false, 
                        .logLocation = "/usr/local/tomcat/logs/CofaxTools.log", 
                        .jspFileTemplate = NULL, 
                        .dataStoreUser = NULL, 
                        .dataStoreClass = NULL, 
                        .searchEngineFileTemplate = NULL, 
                        .dataLog = 1, 
                        .log = 1, 
                        .dataStoreInitConns = NAN, 
                        .dataStorePassword = NULL, 
                        .logMaxSize = "", 
                        .templateOverridePath = NULL
                    }
                }, 
                .servlet_class = "org.cofax.cms.CofaxToolsServlet"
            }
        }, 
        .servlet_mapping = {
            .cofaxCDS = "/", 
            .cofaxEmail = "/cofaxutil/aemail/*", 
            .cofaxAdmin = "/admin/*", 
            .fileServlet = "/static/*", 
            .cofaxTools = "/tools/*"
        }, 
        .taglib = {
            .taglib_uri = "cofax.tld", 
            .taglib_location = "/WEB-INF/tlds/cofax.tld"
        }
    }
};

